"""Delete in table OrderItems UniqueConstraint

Revision ID: db099cd302f8
Revises: a8d2c128c926
Create Date: 2024-08-19 16:35:10.853585

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db099cd302f8"
down_revision: Union[str, None] = "a8d2c128c926"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_order_items", "orderitems", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_order_items", "orderitems", ["basket_id", "product_id"]
    )
    # ### end Alembic commands ###
